import coronary from './coronary.js?v=a35';
import omentum from './omentum.js?v=a35';
import sinusoid from './sinusoid.js?v=a35';
import carotid from './carotid.js?v=a35';
import stomach from './stomach.js?v=a35';
import glomerulus from './glomerulus.js?v=a35';
import islet from './islet.js?v=a35';
import villi from './villi.js?v=a35';
import { withPlate } from './plates.js?v=a35';
export const MAPS=[coronary,omentum,sinusoid,carotid,stomach,glomerulus,islet,villi].map(withPlate);
export const getMap=key=>MAPS.find(map=>map.key===key&&map.ready)||MAPS[0];
